---
title: "Baseball"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Lahman)
library(tidyverse)
library(dslabs)
ds_theme_set()

Teams %>% filter(yearID %in% 1961:2001) %>%
    mutate(HR_per_game = HR / G, R_per_game = R / G) %>%
    ggplot(aes(HR_per_game, R_per_game)) + 
    geom_point(alpha = 0.5)

Teams %>% filter(yearID %in% 1961:2001) %>%
    mutate(SB_per_game = SB / G, R_per_game = R / G) %>%
    ggplot(aes(SB_per_game, R_per_game)) + 
    geom_point(alpha = 0.5)

Teams %>% filter(yearID %in% 1961:2001) %>%
    mutate(BB_per_game = BB / G, R_per_game = R / G) %>%
    ggplot(aes(BB_per_game, R_per_game)) + 
    geom_point(alpha = 0.5)

 Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(X3B_per_game = X3B/G, X2B_per_game = X2B/G) %>%
    ggplot(aes(X3B_per_game, X2B_per_game)) + 
    geom_point(alpha = 0.5)
 
 
```
```{r}
library(tidyverse)
library(HistData)
data("GaltonFamilies")
set.seed(1983)

galton_heights <- GaltonFamilies %>%
  filter(gender == "male") %>%
  group_by(family) %>%
  sample_n(1) %>%
  ungroup() %>%
  select(father, childHeight) %>%
  rename(son = childHeight)
  
galton_heights %>% 
  summarize(mean(father), sd(father), mean(son), sd(son))

galton_heights %>%
  ggplot(aes(father,son)) +
  geom_point(alpha =0.5)

galton_heights %>% summarize( r=cor(father,son)) %>% pull(r)
```
```{r}
# compute sample correlation
R <- sample_n(galton_heights, 25, replace = TRUE) %>%
  summarize( r= cor(father,son))
R

# Monte Carlo simulation to show distribution of sample correlation
B <- 1000
N <- 50
R <- replicate(B,{
  sample_n(galton_heights, N, replace =TRUE) %>%
  summarize( r= cor(father,son)) %>%
  pull(r)
})

qplot(R, geom = "histogram", binwidth = 0.05, color = I("black"))

# expected value and standard error
mean(R)
sd(R)

# QQ-plot to evaluate whether N is large enough
data.frame(R) %>%
  ggplot(aes(sample = R)) +
  stat_qq() +
  geom_abline(intercept = mean(R), slope = sqrt((1-mean(R)^2)/(N-2)))

```
```{r}
Teams %>% filter(yearID %in% 1961:2001 ) %>% 
   summarize( r= cor(X2B/G, X3B/G)) 
```
```{r}
# number of fathers with height 72 or 72.5 inches
sum(galton_heights$father == 72)
sum(galton_heights$father == 72.5)

# predicted height of a son with a 72 inch tall father
conditional_avg <- galton_heights %>%
  filter(round(father) == 72) %>%
  summarize(avg = mean(son)) %>%
             pull (avg)

# stratify fathers' heights to make a boxplot of son heights
galton_heights %>% mutate(father_strata = factor(round(father))) %>%
  ggplot(aes(father_strata,son)) +
  geom_boxplot() +
  geom_point()

# center of each boxplot
galton_heights %>% mutate(father = round(father)) %>%
  group_by(father) %>%
  summarize(son_conditional_avg = mean(son)) %>%
  ggplot(aes(father,son_conditional_avg))+
  geom_point()

# calculate values to plot regression line on original data
mu_x <- mean(galton_heights$father)
mu_y <- mean(galton_heights$son)
s_x <- sd(galton_heights$father)
s_y <- sd(galton_heights$son)
r <- cor(galton_heights$father,galton_heights$son)  
m <- r * s_y / s_x
b <- mu_y - m*mu_x

# add regression line to plot
galton_heights %>%
  ggplot(aes(father,son)) +
  geom_point(alpha = 0.5) +
  geom_abline(intercept = b, slope = m)
```


```{r}
galton_heights %>% 
  mutate(z_father = round((father-mean(father))/sd(father))) %>%
  filter(z_father %in% -2:2) %>%
  ggplot() +
  stat_qq(aes(sample = son)) +
  facet_wrap( ~ z_father)
         
```
```{r}
m_1 <- r * s_y / s_x
b_1 <- mu_y - m_1*mu_x

m_2 <- r * s_x / s_y
b_2 <- mu_x - m_2 * mu_y

```

```{r}
set.seed(1989, sample.kind = "Rounding")
library(HistData)
data("GaltonFamilies")

female_heights <- GaltonFamilies %>%
  filter(gender == "female") %>%
  group_by(family) %>%
  sample_n(1) %>%
  ungroup() %>%
  select(mother, childHeight) %>%
  rename(daughter  = childHeight)

mean(female_heights$mother); sd(female_heights$mother)
mean(female_heights$daughter); sd(female_heights$daughter)
cor(female_heights$mother,female_heights$daughter)
```

