---
title: "Baseball"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Lahman)
library(tidyverse)
library(dslabs)
ds_theme_set()
# find regression line for predicting runs from BBs
bb_slope <- Teams %>% filter(yearID %in% 1961:2001) %>%
    mutate(BB_per_game = BB / G, R_per_game = R / G) %>%
    lm(R_per_game ~ BB_per_game, data = .) %>% 
    .$coef %>% 
  .[2]
bb_slope
# compute regression line for predicting runs from singles
singles_slope <- Teams %>% filter(yearID %in% 1961:2001) %>%
     mutate(S_per_game = (H-HR-X3B-X2B) / G, R_per_game = R / G) %>%
    lm(R_per_game ~ S_per_game, data = .) %>% 
    .$coef %>% 
  .[2]
singles_slope

# calculate correlation between HR, BB and singles
Teams %>% 
  filter(yearID %in% 1961:2001 ) %>% 
  mutate(Singles = (H-HR-X2B-X3B)/G, BB = BB/G, HR = HR/G) %>%  
  summarize(cor(BB,HR),cor(Singles,HR), cor(BB,Singles))
 
```
```{r}
# stratify HR per game to nearest 10, filter out strata with few points
dat <- Teams %>% filter(yearID %in% 1961:2001) %>%
  mutate(HR_strata = round(HR/G,1),
         BB_per_game = BB/G,
         R_per_game = R/G) %>%
  filter(HR_strata >= 0.4 & HR_strata <= 1.2)

# scatter plot for each HR stratum
dat %>% ggplot(aes(BB_per_game,R_per_game)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm")+
  facet_wrap(~ HR_strata)

# calculate slope of regression line after stratifying by HR
dat %>% group_by(HR_strata) %>%
  summarize(slope = cor(BB_per_game,R_per_game)*sd(R_per_game)/sd(BB_per_game))

# stratify by BB
dat <- Teams %>% filter(yearID %in% 1961:2001) %>%
  mutate(BB_strata = round(BB/G,1),
         HR_per_game = HR/G,
         R_per_game = R/G) %>%
  filter(BB_strata >= 2.8 & BB_strata <= 3.9)

# scatterplot for each BB stratum
dat %>% ggplot(aes(HR_per_game,R_per_game)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm")+
  facet_wrap(~ BB_strata)

#slope of regression line after stratifying by BB
dat %>% group_by(BB_strata) %>%
  summarize(slope = cor(R_per_game,HR_per_game)*sd(R_per_game)/sd(HR_per_game))
```
```{r}
# compute RSS for any pair of beta0 and beta1 in Galton's data
library(HistData)
data("GaltonFamilies")
set.seed(1983)
galton_heights <- GaltonFamilies %>%
  filter(gender == "male") %>%
  group_by(family) %>%
  sample_n(1) %>%
  ungroup() %>%
  select(father,childHeight) %>%
  rename(son = childHeight) 
rss <-function(beta0,beta1) {
  resid <- galton_heights$son - (beta0 + beta1*galton_heights$father)
  return(sum(resid^2))
}

# plot RSS as a function of beta1 when beta0=25
beta1 = seq(0,1,len = nrow(galton_heights))
results <- data.frame(beta1 = beta1, rss = sapply(beta1,rss,beta0 =36))
results %>% ggplot(aes(beta1,rss)) + geom_line() 

```
```{r}
fit <- lm(son ~ father, data = galton_heights)
fit
summary(fit)
```
```{r}
# Monte Carlo simulation
B <- 1000
N <- 50

lse <- replicate(B,{
  sample_n(galton_heights, N, replace =TRUE) %>%
    lm(son~father, data =.) %>%
    .$coef
})
lse <- data.frame(beta_0 = lse[1,],beta_1 = lse[2,])

# Plot the distribution of beta_0 and beta_1
library(gridExtra)
p1<- lse %>% ggplot(aes(beta_0)) + geom_histogram(binwidth = 5, color ="black" )
p2<- lse %>% ggplot(aes(beta_1)) + geom_histogram(binwidth = 0.1, color ="black" )
grid.arrange(p1,p2,ncol=2)

#summary statistics
sample_n(galton_heights, N, replace = TRUE) %>%
  lm(son ~ father, data =.) %>%
  summary %>%
  .$coef

lse %>% summarize(se_0 = sd(beta_0), se_1 = sd(beta_1))

lse %>% summarize(cor(beta_0,beta_1))

cor(lse$beta_0,lse$beta_1)

lse <- replicate(B, {
      sample_n(galton_heights, N, replace = TRUE) %>%
      mutate(father = father - mean(father)) %>%
      lm(son ~ father, data = .) %>% .$coef 
})

cor(lse[1,],lse[2,])
```
```{r}
#plot predictions and confidence interval
galton_heights %>%  mutate(father = father - mean(father)) %>%
  ggplot(aes(father,son)) +
  geom_point () +
  geom_smooth(method = "lm")

#predict Y directly
fit <- galton_heights %>% lm(son ~ father, data = .)
Y_hat <- predict(fit,se.fit = TRUE)
names(Y_hat)

#plot best fit line
galton_heights %>% mutate(Y_hat = predict(lm(son~father,data= .))) %>%
  ggplot(aes(father,Y_hat)) +
  geom_line()


```

```{r}
library(Lahman)
library(tidyverse)
library(dslabs)
# find regression line for predicting runs from BBs and Home Runs
bb_coef <- Teams %>% filter(yearID %in% 1961:2001) %>%
    mutate(BB_per_game = BB / G, HR_per_game = HR / G, R_per_game = R / G) %>%
    lm(R_per_game ~ BB_per_game + HR_per_game, data = .) %>% 
    .$coef
bb_coef
```
```{r}
  model <- lm(son ~ father, data = galton_heights)
predictions <- predict(model, interval = c("confidence"), level = 0.95)
data <- as.tibble(predictions) %>% bind_cols(father = galton_heights$father)

ggplot(data, aes(x = father, y = fit)) +
    geom_line(color = "blue", size = 1) + 
    geom_ribbon(aes(ymin=lwr, ymax=upr), alpha=0.2) + 
    geom_point(data = galton_heights, aes(x = father, y = son))
```

```{r}
set.seed(1989, sample.kind="Rounding") #if you are using R 3.6 or later
library(HistData)
data("GaltonFamilies")
options(digits = 3)    # report 3 significant digits

female_heights <- GaltonFamilies %>%     
    filter(gender == "female") %>%     
    group_by(family) %>%     
    sample_n(1) %>%     
    ungroup() %>%     
    select(mother, childHeight) %>%     
    rename(daughter = childHeight)

fit <- female_heights %>% lm(mother ~ daughter, data = .) 
fit$coef

predict(fit)[1]
female_heights$mother[1]
```
```{r}
library(Lahman)
bat_02 <- Batting %>% filter(yearID == 2002) %>%
    mutate(pa = AB + BB, singles = (H - X2B - X3B - HR)/pa, bb = BB/pa) %>%
    filter(pa >= 100) %>%
    select(playerID, singles, bb)

bat_01 <- Batting %>% filter(yearID %in% 1999:2001) %>%
    mutate(pa = AB + BB, singles = (H - X2B - X3B - HR)/pa, bb = BB/pa) %>%
    filter(pa >= 100) %>%
    group_by(playerID) %>%
    summarize(mean_singles = mean(singles), mean_bb = mean(bb))

sum(bat_01$mean_singles > 0.2)
sum(bat_01$mean_bb > 0.2)

dat <- inner_join(bat_01,bat_02)
cor(dat$singles,dat$mean_singles)
cor(dat$bb,dat$mean_bb)

p1 <- dat %>% ggplot(aes(mean_singles,singles)) + geom_point()
p2 <- dat %>% ggplot(aes(mean_bb,bb)) + geom_point()
library(gridExtra)
grid.arrange(p1,p2,ncol=2)

dat %>% lm(singles ~ mean_singles, data = .) %>%  .$coef
dat %>% lm(bb ~ mean_bb, data = .) %>%  .$coef
```
```{r}
dat <- Teams %>% filter(yearID %in% 1961:2001) %>%
  mutate(HR = round(HR/G, 1), 
         BB = BB/G,
         R = R/G) %>%
  select(HR, BB, R) %>%
  filter(HR >= 0.4 & HR<=1.2) 

# define a function to extract slope from lm
get_slope <- function(data) {
  fit <- lm(R ~ BB, data = data)
  data.frame(slope = fit$coefficients[2],
             se = summary(fit)$coefficient[2,2])
}

# return the desired data frame
dat %>% group_by(HR) %>%
  do(get_slope(.))

# not the desired output: a column containing data frames
dat %>%  
  group_by(HR) %>%
  do(slope = get_slope(.))

# data frames with multiple rows will be concatenated appropriately
get_lse <- function(data){
  fit <- lm(R ~ BB, data = data)
  data.frame(term = names(fit$coefficients),
    estimate = fit$coefficients, 
    se = summary(fit)$coefficient[,2])
}

dat %>%  
  group_by(HR) %>%
  do(get_lse(.))
```
```{r}
# use tidy to return lm estimates and related information as a data frame
library(broom)
fit <- lm(R ~ BB, data = dat)
tidy(fit)
summary(fit)

# add confidence intervals with tidy
tidy(fit, conf.int = TRUE)

#pipeline with lm, do, tidy
dat %>% group_by(HR) %>% 
  do(tidy(lm(R~BB, data = .), conf.int = TRUE)) %>%
  filter(term == "BB") %>%
  select(HR, estimate, conf.low, conf.high)

#make ggplots
dat %>% group_by(HR) %>%
  do(tidy(lm(R~BB, data = .),conf.int = TRUE)) %>%
  filter(term == "BB") %>%
  select(HR, estimate, conf.low, conf.high) %>%
  ggplot(aes(HR, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_errorbar() +
  geom_point()

#inspect with glance
glance(fit)
```
```{r}
dat <- Teams %>% filter(yearID %in% 1961:2001) %>%
  mutate(HR = HR/G,
         R = R/G) %>%
  select(lgID, HR, BB, R) 

dat %>% 
  group_by(lgID) %>% 
  do(tidy(lm(R ~ HR, data = .), conf.int = T)) %>% 
  filter(term == "HR") 
```
```{r}
library(tidyverse)
library(HistData)
data("GaltonFamilies")
set.seed(1, sample.kind = "Rounding") # if you are using R 3.6 or later
galton <- GaltonFamilies %>%
    group_by(family, gender) %>%
    sample_n(1) %>%
    ungroup() %>% 
    gather(parent, parentHeight, father:mother) %>%
    mutate(child = ifelse(gender == "female", "daughter", "son")) %>%
    unite(pair, c("parent", "child"))

head(galton)

galton %>% group_by(pair) %>% summarise(n = n())

get_cor <- function(data){
  corr <- data %>% cor(childHeight,parentHeight)
  data.frame(corr = corr)
}

galton %>% group_by(pair) %>% summarize(corr = cor(childHeight,parentHeight))
```
```{r}
library(broom)

#pipeline with lm, do, tidy
galton %>% group_by(pair) %>% 
  do(tidy(lm(childHeight~parentHeight, data = .), conf.int = TRUE)) %>%
  filter(term == "parentHeight") %>%
  pull(estimate)

galton %>% group_by(pair) %>% 
  do(tidy(lm(childHeight~parentHeight, data = .), conf.int = TRUE)) %>%
  filter(term == "parentHeight") %>%
  ggplot(aes(pair, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_errorbar() +
  geom_point()
```

